pipeline {
    agent any

    environment {
        // Update this with your GitHub Personal Access Token
        GITHUB_TOKEN = credentials('github_jenkins')
        RENDER_TOKEN = credentials('renderpwd')
        DOCKER_IMAGE_TAG = '1.9'
    }

    stages {
        stage('Clone Repository') {
            steps {
                script {
                    def repoUrl = 'https://github.com/ARCHIT1607/UnitySpace.git'
                    def branchName = 'version-3'

                    // Clone the repository with authentication
                    git credentialsId: env.GITHUB_TOKEN,
                        url: repoUrl,
                        branch: branchName,
                        credentialsProvider: [
                            $class: 'UsernamePasswordCredentialsProvider'
                        ]
                }
            }
        }

     stage('Docker Build') {
            steps {
                dir('unityspace') {
                    // Navigate to the UnitySpace folder
                    bat 'docker build -t architdev/unityspace:1.9 .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                   withCredentials([string(credentialsId: 'dockerhubpwd', variable: 'dockerhubpwd')]) {
                        bat 'docker login -u architdev -p Bluestar@16'
                        bat 'docker push architdev/unityspace:1.9'
                    }
                }
            }
        }
        stage('Deploy to Render') {
            steps {
                script {

                    def renderToken = env.RENDER_TOKEN
                    def serviceName = 'unityspace-api'
                    bat """
                         curl -X GET -H "Authorization: Bearer  $renderToken" "https://api.render.com/deploy/srv-cjmb6iocfp5c73b0smn0?key=6aGObVFR8xw&imgURL=docker.io/architdev/unityspace:1.9"
                    """
                }
            }
        }
        // Add more stages as needed for your build and deployment process
    }
}
